from collections.abc import Iterator

import pytest


_SETTINGS_ENV_KEYS = (
    "DATABASE_URL",
    "CORRELIA_DATABASE_URL",
    "CORRELIA_ENVIRONMENT",
    "CORRELIA_LOG_LEVEL",
    "CORRELIA_RULES_PATH",
    "CORRELIA_TOPOLOGY_PATH",
    "CORRELIA_PLUGINS_PATH",
    "CORRELIA_API_AUTH_ENABLED",
    "CORRELIA_OPERATOR_API_TOKEN",
    "CORRELIA_INGRESS_API_TOKEN",
    "CORRELIA_EXPOSE_READYZ",
    "CORRELIA_EXPOSE_METRICS",
    "CORRELIA_MIGRATION_REPORT_PATH",
    "CORRELIA_MAX_BODY_BYTES",
    "CORRELIA_MAX_BODY_BYTES_OPERATOR",
    "CORRELIA_MAX_BODY_BYTES_INGRESS",
    "CORRELIA_MAX_BODY_BYTES_METRICS",
    "CORRELIA_MAX_BODY_BYTES_READYZ",
    "CORRELIA_MAX_BODY_BYTES_HEALTH",
    "CORRELIA_RATE_LIMIT_ENABLED",
    "CORRELIA_RATE_LIMIT_REQUESTS_OPERATOR",
    "CORRELIA_RATE_LIMIT_WINDOW_SECONDS_OPERATOR",
    "CORRELIA_RATE_LIMIT_REQUESTS_INGRESS",
    "CORRELIA_RATE_LIMIT_WINDOW_SECONDS_INGRESS",
    "CORRELIA_RATE_LIMIT_REQUESTS_METRICS",
    "CORRELIA_RATE_LIMIT_WINDOW_SECONDS_METRICS",
    "CORRELIA_RATE_LIMIT_REQUESTS_READYZ",
    "CORRELIA_RATE_LIMIT_WINDOW_SECONDS_READYZ",
    "CORRELIA_RATE_LIMIT_REQUESTS_HEALTH",
    "CORRELIA_RATE_LIMIT_WINDOW_SECONDS_HEALTH",
    "CORRELIA_RATE_LIMIT_SWEEP_INTERVAL_SECONDS",
    "CORRELIA_AUDIT_RAW_PAYLOAD_MAX_BYTES",
    "CORRELIA_AUDIT_RAW_PAYLOAD_HMAC_KEY",
)


@pytest.fixture(autouse=True)
def clean_settings_env(monkeypatch: pytest.MonkeyPatch) -> Iterator[None]:
    for key in _SETTINGS_ENV_KEYS:
        monkeypatch.delenv(key, raising=False)
    yield
